### ISSUE TITLE
External sea-surface height anomaly removed?

### ISSUE THREAD

**Issue by alex-robinson** [palma-ice/isostasy#14]
It is clear that with the latest version of isostasy, it is possible to calculate a spatially variable sea-surface height (ssh) around the domain that depends on what is happening in the domain. However, if a far-field perturbation to ssh is also needed, this seems to be missing from the update step:

```
isos_update(isos, H_ice, time, dwdt_corr) 
```

Can this be reintroduced, or did it simply get moved somewhere else?

**Comment by JanJereczek** [comment]
The SSH can be decomposed as:

$ \mathrm{SSH} = \mathrm{BSL} + \Delta \mathrm{SSH},$

with BSL the barystatic sea level (scalar) and $\Delta \mathrm{SSH}$ the SSH perturbation (matrix). The difference that we would get from the far field would be coming mostly from the BSL as far as I understand. For instance, -130m at LGM. Is this what you mean?

**Comment by alex-robinson** [comment]
Yes, so the $BSL$ in your equation, I think, should be an argument to the update routine. I see in the code that `isos%now%bsl` exists, but I didn't see it being updated.

**Comment by alex-robinson** [comment]
This was resolved by recent PR.
